import AsideNavbar from "@/components/common/AsideNavbar";
import Navbar from "@/components/common/Navbar";

export const metadata = {
  title: "Dashboard",
  description: "Generated by create next app",
};

const DashboardLayout = ({ children }) => {
  return (
    <div className="flex h-screen overflow-hidden bg-gray-50 dark:bg-gray-900">
      <aside className="hidden md:flex md:flex-col w-64 bg-white dark:bg-gray-800">
        <AsideNavbar />
      </aside>
      <div className="flex-1 flex flex-col">
        <header className="bg-white h-20 flex items-center px-4 md:px-6">
          <Navbar />
        </header>
        <main className="flex-1 overflow-y-auto p-6">{children}</main>
      </div>
    </div>
  );
};

export default DashboardLayout;
