import AsideNavbar from "@/components/common/AsideNavbar";
import Navbar from "@/components/common/Navbar";

export const metadata = {
  title: "Dashboard",
  description: "Generated by create next app",
};

const DashboardLayout = ({ children }) => {
  return (
    <div className="w-full h-screen flex overflow-hidden">
      <aside className="hidden md:block w-1/6 h-full bg-gray-50">
        <AsideNavbar />
      </aside>
      <div className="flex-1 h-full flex flex-col">
        <header className="h-20 bg-gray-50 border-b flex items-center px-4 sticky top-0 z-10">
          <Navbar />
        </header>
        <main className="flex-1 overflow-y-auto px-6 py-4 bg-white">
          {children}
        </main>
      </div>
    </div>
  );
};

export default DashboardLayout;
